### ISSUE TITLE
Big Number Viz Type: Internal Service Error

### ISSUE THREAD

**Issue by samuel-peterson** [airbnb/caravel#426] opened 2016-05-03 07:51 UTC
When I use a time window that contains no rows, the report returns an Internal Service error rather than 0, which is the desired output in this situation.

e.g. When no orders were created yesterday, and use Large number as the viz-type for the slice that displays yesterday's orders, the Internal Service error is displayed.

I Believe this is because the viz-type doesn't handle empty query tables the way it should.  I intend to work on this when I have time, but thought I should post this before I do on the off chance someone else is interested in looking in to it.

**Comment by mistercrunch** [comment] 2016-05-04 05:53
Couldn't reproduce, are you using "Big Number with Trendline"?
<img width="769" alt="screen shot 2016-05-03 at 10 52 07 pm" src="https://cloud.githubusercontent.com/assets/487433/15006083/be23879e-1181-11e6-9b9e-e91e250abf0b.png">

**Comment by xrmx** [comment] 2016-08-08 16:12
3 months without reporter feedback, closing.

**Closed by xrmx** 2016-08-08 16:12 UTC
Labels: bug_cant_reproduce
