### ISSUE TITLE
`npm run dev` in caravel/caravel/assets throws error

### ISSUE THREAD

**Issue by shkr** [airbnb/caravel#820] opened 2016-07-26 07:42 UTC
I cloned the caravel repository. I installed npm as prescribed in Contributing.md. Then after the required steps, I ran `npm run dev` to run the local caravel installation.

I see an error log in the console

```

ERROR in ./javascripts/caravel-select2.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../node_modules/jquery-ui/themes/base/jquery-ui.css in /Users/shashank/Documents/repositories/caravel/caravel/assets/javascripts
 @ ./javascripts/caravel-select2.js 5:0-62

```

**Comment by georgeke** [comment] 2016-07-27 05:42
Hmm, do you have the latest version of master? This is a duplicate of https://github.com/airbnb/caravel/issues/768 and should have been fixed.

Try uninstalling jquery-ui and re-rerunning `npm install` to get the correct build version.

**Comment by xrmx** [comment] 2016-08-08 19:32
@shkr is this fixed for you? If so please close the issue, thanks.

**Comment by kusumakarb** [comment] 2016-08-10 08:41
The error still persists. I had to do `rm -rf /node_modules/jquery-ui` and then `npm i jquery-ui@1.10.5 --save` as given in the previous thread.

**Comment by xrmx** [comment] 2016-08-10 09:06
@kusumakarb with a fresh master `npm install` correctly install jquery-ui@1.10.5 here.

**Closed** 2016-09-17 14:59 UTC
Labels: waiting_for_validation
