### ISSUE TITLE
Issue after downloading fix for 356

### ISSUE THREAD

**Issue by shahneil88** [airbnb/caravel#380] opened 2016-04-20 08:09 UTC
Hi,

I wanted to install fix for #356 
I downloaded a tar file and ran setup.py.
I ran command `caravel db upgrade` 

I still see the issue which I saw in #356 , with a different error.

![screen shot 2016-04-20 at 4 05 50 pm](https://cloud.githubusercontent.com/assets/7529421/14667433/dc152e94-0711-11e6-8232-b0522e1f4f29.png)

I also do not see any slice/Dashboard. They are Blank.
Did I upgrade correctly using tarball? or missed something?

![screen shot 2016-04-20 at 4 08 16 pm](https://cloud.githubusercontent.com/assets/7529421/14667491/2a938f34-0712-11e6-8a7e-207d8139adfb.png)

**Comment by mistercrunch** [comment] 2016-04-20 20:37
Mmmmh, not sure what you did but I can't reproduce for sure. Maybe wait for `0.8.9`, should be out this week

**Comment by shahneil88** [comment] 2016-04-21 05:31
@mistercrunch - Sure. Thank you. I will wait for 0.8.9 release.

**Comment by shahneil88** [comment] 2016-04-26 02:04
@mistercrunch - Any tentative date on release of `0.8.9` release? I have set up caravel on my production and just waiting for this fix to be out to start sharing dashboards with wider group of people.

**Comment by xrmx** [comment] 2016-08-08 16:09
0.8.9 has been out since a few, closing.

**Closed by xrmx** 2016-08-08 16:09 UTC
Labels: bug_cant_reproduce
