### ISSUE TITLE
time series line chart has a date shift

### ISSUE THREAD

**Issue by SimpleExpress** [airbnb/caravel#976] opened 2016-08-18 02:52 UTC
I used time series line chart to display the data trending, but the value was shifted by 1 day, e.g. the value on 2016-05-01 was 23801, but actually the value was plotted on 2016-04-30. Will you help to investigate it or give some suggestions. Thanks a lot.

the data exported by caravel:
![image](https://cloud.githubusercontent.com/assets/1047330/17760267/249bf15c-6531-11e6-91ca-a20383f593d9.png)

the plot actually made by caravel:
![image](https://cloud.githubusercontent.com/assets/1047330/17760285/4c999c40-6531-11e6-8cc7-18e4f666fbe2.png)

**Comment by xrmx** [comment] 2016-08-18 09:37
This looks like a duplicate of #763 , right?

**Comment by RiseOfApes** [comment] 2016-08-19 03:14
I have the same problem.How can  I make up it with out add "at time zone" to the query every time #763

**Comment by xrmx** [comment] 2016-08-19 13:28
Closing as duplicate of #763

**Closed by xrmx** 2016-08-19 13:28 UTC

**Comment by galinaalperovich** [comment] 2019-03-25 12:48
Seems like this problem still persists. How to disable the UTC conversion?

**Comment by mlieqo** [comment] 2019-05-03 11:20
I had the same problem. Solved it with setting offset value in the datasource settings!
