### ISSUE TITLE
MySQL as Backend with Druid as datasource

### ISSUE THREAD

**Issue by lony25** [airbnb/caravel#518] opened 2016-05-26 08:52 UTC
When using mysql as URI scheme in caravel_config.py, everything works fine.
I could add druid cluster. When I try to refresh druid metadata, it throws following error:

sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (_mysql_exceptions.IntegrityError) (1452, 'Cannot add or update a child row: a foreign key constraint fails (`caravel`.`columns`, CONSTRAINT `columns_ibfk_1` FOREIGN KEY (`column_name`) REFERENCES `datasources` (`datasource_name`))')

On debugging, I figured out that while calling sync_to_db, DruidDatasource is trying to modify DruidColumn which I understand is not allowed. 

Could some one help me if I am doing something wrong or is it a valid issue.

OS: Ubuntu 14.04
Druid: 0.9
Caravel: 0.9

Steps to reproduce.
1. Change URI scheme to mysql as instructed in tutorial. Follow tutorial.
2. Add Druid cluster.
3. Do Druid Refresh Metadata.

**Comment by x4base** [comment] 2016-05-27 01:53
Should be related to #466

**Comment by kkalyan** [comment] 2016-06-20 12:23
I ran into same issue, temporary workaround is to remove foreign key

`alter table columns drop foreign key columns_ibfk_1;`

**Comment by xrmx** [comment] 2016-08-09 08:58
Closing as duplicate of #466

**Closed by xrmx** 2016-08-09 08:58 UTC
